# Generated by Django 3.2.7 on 2021-09-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_auto_20210921_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theater.theater'),
        ),
        migrations.CreateModel(
            name='Vars',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=32)),
                ('ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='theater.vars')),
            ],
        ),
    ]
