# Generated by Django 3.2.7 on 2021-09-22 08:39

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_auto_20210921_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theater.theater'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET'),
        ),
    ]
