# Generated by Django 3.2.7 on 2021-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0007_alter_theater_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vars',
            options={'ordering': ['field', 'value'], 'verbose_name': 'Variables', 'verbose_name_plural': 'Variables'},
        ),
        migrations.AddIndex(
            model_name='vars',
            index=models.Index(fields=['field'], name='theater_var_field_b130cc_idx'),
        ),
    ]
