# Generated by Django 3.2.7 on 2021-09-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0008_auto_20210923_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theater',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['name'], name='theater_the_name_d8b3a9_idx'),
        ),
    ]
