# Generated by Django 3.2.7 on 2021-09-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0009_auto_20210923_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaserver',
            name='model',
        ),
        migrations.AddField(
            model_name='mediaserver',
            name='model',
            field=models.ManyToManyField(related_name='model', to='theater.Vars', verbose_name='Mediaserver Model'),
        ),
        migrations.RemoveField(
            model_name='mediaserver',
            name='vendor',
        ),
        migrations.AddField(
            model_name='mediaserver',
            name='vendor',
            field=models.ManyToManyField(related_name='vendor', to='theater.Vars', verbose_name='Mediaserver Vendor'),
        ),
        migrations.AlterField(
            model_name='vars',
            name='value',
            field=models.CharField(max_length=64),
        ),
    ]
