# Generated by Django 3.2.7 on 2021-09-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0010_auto_20210923_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaserver',
            name='model',
        ),
        migrations.AddField(
            model_name='mediaserver',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='theater.vars', verbose_name='Mediaserver Model'),
        ),
        migrations.RemoveField(
            model_name='mediaserver',
            name='vendor',
        ),
        migrations.AddField(
            model_name='mediaserver',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to='theater.vars', verbose_name='Mediaserver Vendor'),
        ),
    ]
