# Generated by Django 3.2.7 on 2021-09-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0011_auto_20210923_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaserver',
            name='model',
            field=models.ForeignKey(limit_choices_to={'value': 'mediaserver.model'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='theater.vars', verbose_name='Mediaserver Model'),
        ),
        migrations.AlterField(
            model_name='mediaserver',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'value': 'mediaserver.vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor', to='theater.vars', verbose_name='Mediaserver Vendor'),
        ),
    ]
