# Generated by Django 3.2.7 on 2021-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0013_auto_20210923_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='isDual',
            field=models.BooleanField(default=False),
        ),
    ]
