# Generated by Django 3.2.7 on 2021-09-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Title')),
                ('full_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full title')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year of release')),
                ('studio', models.CharField(blank=True, max_length=64, null=True, verbose_name='Production studio')),
                ('director', models.CharField(blank=True, max_length=64, null=True, verbose_name='Director')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
