# Generated by Django 3.2.7 on 2021-09-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teka', '0002_cpl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpl',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
