# Generated by Django 3.2.7 on 2021-09-21 02:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KDM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='KDM name')),
                ('dual_projector', models.BooleanField(default=False)),
                ('KDM_text', models.TextField(null=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Key Validity')),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Key Validity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.cpl')),
                ('mediaserver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theater.mediaserver')),
            ],
        ),
    ]
