# Generated by Django 3.2.7 on 2021-09-21 02:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kdm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdm',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
