# Generated by Django 3.2.7 on 2021-09-23 06:04

from django.db import migrations, models
import kdm.models


class Migration(migrations.Migration):

    dependencies = [
        ('kdm', '0003_auto_20210923_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdm',
            name='date_end',
            field=models.DateTimeField(default=kdm.models._now_plus_one_day, verbose_name='End Key Validity'),
        ),
    ]
