# Generated by Django 3.2.7 on 2021-09-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210921_0551'),
        ('kdm', '0004_alter_kdm_date_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kdm',
            options={'default_permissions': ('add', 'view'), 'verbose_name': 'KDM'},
        ),
        migrations.AlterField(
            model_name='kdm',
            name='cpl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.cpl', verbose_name='CPL'),
        ),
    ]
