# Generated by Django 3.2.7 on 2021-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdm', '0005_auto_20210923_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kdm',
            old_name='KDM_text',
            new_name='KDM_content',
        ),
        migrations.AddField(
            model_name='kdm',
            name='TDL_content',
            field=models.TextField(null=True),
        ),
    ]
