# Generated by Django 3.2.7 on 2021-09-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0014_screen_isdual'),
        ('kdm', '0006_auto_20210923_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kdm',
            name='TDL',
        ),
        migrations.AddField(
            model_name='kdm',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theater.screen'),
        ),
    ]
